site_name: My Teams

extra_css:
  - "styles/extra.css"

nav:
  - Introduction:
    - "Home Page" : "index.md"
  - Commands:
    - "Commands"  : "commands.md"
  - Error Codes:
    - "Error Codes" : "error_codes.md"

theme:
  name: material
  logo: "styles/logo.svg"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/moon-waxing-crescent
        name: Switch to dark mode
      primary: teal
      accent: blue
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
